[package]
name = "crdt-testdata"
version = "0.0.0"
authors = ["Seph Gentle <me@josephg.com>"]
edition = "2021"

[dependencies]
flate2 = { version = "1.0.22", features = ["zlib-ng-compat"], default-features = false }
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
